### ISSUE TITLE
Ixnetwork Rest Port rejects requests sometimes

### ISSUE THREAD

**Issue by subha-py** [ajbalogh/ixnetwork_client_python#5] opened 2018-02-16 08:36 UTC
Hi,
When we are _**making thousands of requests to Ixnetwork rest port from ixn_client_python**_, it **rejects** the request **sometimes**(very rarely, once in thousands). This give an connection refused error at socket interface and disrupts the automation scripts. We can try catch in our scripts or may try with some sleep, but that will not be the best possible solution.

Can we put a try catch block in IxnHttp.py line 188, and retry for a few times before discarding the request?
Or there will be any collateral if we do that.

- **Error Code:**

`Traceback (most recent call last):
  File "ConfigConverter.py", line 122, in <module>
    config_convertor.convert()
  File "ConfigConverter.py", line 35, in convert
    N2xConverter(self._from_tree, self._ixnhttp).convert()
  File "/home/subha/PycharmProjects/configuration_converter/N2xConverter.py", line 51, in convert
    N2XconvertStreamGroupList(self)
  File "/home/subha/PycharmProjects/configuration_converter/N2XconvertStreamGroupList.py", line 19, in __init__
    self._convert_agt_stream_group_list()
  File "/home/subha/PycharmProjects/configuration_converter/N2XconvertStreamGroupList.py", line 439, in _convert_agt_stream_group_list
    frameSize = self.highLevelStream.query.clear().node('frameSize', properties=['*']).go().frameSize
  File "/home/subha/configuration_converter/lib/python3.5/site-packages/ixnetwork/IxnQuery.py", line 97, in go
    async_response = self._ixnhttp.post('/operations/query', self._query)
  File "/home/subha/configuration_converter/lib/python3.5/site-packages/ixnetwork/IxnHttp.py", line 152, in post
    response = self._send_recv('POST', url, payload, fid, file_content)
  File "/home/subha/configuration_converter/lib/python3.5/site-packages/ixnetwork/IxnHttp.py", line 188, in _send_recv
    self._connection.request(method, url, json.dumps(payload), headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`

- **If the above code is hard to read please refer this picture:**

![capture](https://user-images.githubusercontent.com/20321010/36299285-4b3881d6-1322-11e8-8d8f-6d00f898ef55.PNG)

**Comment by ajbalogh** [comment] 2018-02-16 16:02
Is there any error on the ixnetwork server log. You can enable full trace logs on the command line using -tracelevel All kDebug.  Is the ixnetwork server instance a windows gui instance or linux middleware instance?

**Comment by ajbalogh** [comment] 2018-02-16 17:23
Adding a try catch in the client code does not address the root cause in that the server has refused the connection. This needs to be investigated and fixed in IxNetwork self host server code. At this time I have been able to run over 100000 transactions with connection error.

**Comment by whandjr** [comment] 2018-02-16 18:38
With connection error?

Thanks,
Wes

Sent from Samsung. Please excuse typos.

On February 16, 2018 9:24:00 AM ajbalogh <notifications@github.com> wrote:

Adding a try catch in the client code does not address the root cause in that the server has refused the connection. This needs to be investigated and fixed in IxNetwork self host server code. At this time I have been able to run over 100000 transactions with connection error.

**Comment by ajbalogh** [comment] 2018-02-16 18:52
found and fixed an issue with redirects in that content was not being read which was causing connection issues on subsequent requests.

**Closed by ajbalogh** 2018-02-16 18:52 UTC
